### ISSUE TITLE
NullPointerException when using VanishNoPacket

### ISSUE THREAD

**Issue by graywolf336** [rogermb/BukkitSpeak#3] opened 2012-10-24 21:29 UTC
When using VanishNoPacket to silence a player's join and to join vanished so people can't see me login, a NPE occurs with BukkitSpeak:

``` java
10-24 23:26:46 [INFO] graywolf336[/76.92.190.198:64880] logged in with entity id 3566 at ([desert] 1.69999998$
2-10-24 23:26:46 [INFO] [VanishNoPacket] graywolf336 disappeared.
2-10-24 23:26:46 [SEVERE] Could not pass event PlayerJoinEvent to BukkitSpeak v0.61-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.minecraft.server.ServerConfigurationManagerAbstract.c(ServerConfigurationManagerAbstract.java:161)
        at net.minecraft.server.ServerConfigurationManagerAbstract.a(ServerConfigurationManagerAbstract.java:92)
        at net.minecraft.server.NetLoginHandler.d(NetLoginHandler.java:129)
        at net.minecraft.server.NetLoginHandler.c(NetLoginHandler.java:42)
        at net.minecraft.server.DedicatedServerConnectionThread.a(DedicatedServerConnectionThread.java:44)
        at net.minecraft.server.DedicatedServerConnection.b(SourceFile:29)
        at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:561)
        at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:213)
        at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:474)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.NullPointerException
        at net.but2002.minecraft.BukkitSpeak.Commands.BukkitSpeakCommand.replaceKeys(BukkitSpeakCommand.java:178)
        at net.but2002.minecraft.BukkitSpeak.ChatListener.replaceKeys(ChatListener.java:124)
        at net.but2002.minecraft.BukkitSpeak.ChatListener.onPlayerJoin(ChatListener.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)s!
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
        ... 14 more
```

**Comment by rogermb** [comment] 2012-10-25 16:46
Kay, I'll look into it and **maybe** even add VanishNoPacket integration.

**Comment by rogermb** [comment] 2012-10-25 16:48
By the way, thanks so much for just reporting those bugs!
I hate it if there are obvious problems when the plugin is used in combination with another plugin, but I never get to hear about it because I don't use said plugin on my server for testing, and nobody submits a bug report to this page or the Bukkit Dev ticket system ^^

**Comment by graywolf336** [comment] 2012-10-25 17:16
I know the feeling man, people rarely submit bugs to my plugin's page lol

Btw it does it on logging out too.

**Comment by rogermb** [comment] 2012-10-25 17:22
Kay, and it only happens when logging in and out **vanished**?

**Comment by graywolf336** [comment] 2012-10-25 17:23
I believe so, as it only happens when myself and my other server owner login and out since we're the only ones who login and out vanished.

**Comment by rogermb** [comment] 2012-10-25 17:28
Okay, as far as I can see, a value has been assigned to null in the HashMap, so I know for a fact that it doesn't set the player of the event to null, and it really has to be the join message which gets set to null.
I guess this has been implemented so chat plugins don't send login and logout messages,
and it also gives me quite a nice hook to implement Vanish without even having to reference the library.
I think it will suffice to do: if (e.getJoinMessage() == null) return;

**Comment by graywolf336** [comment] 2012-10-25 17:33
Yeah I think that will work

**Comment by rogermb** [comment] 2012-10-25 17:38
Can you test [Build 102](http://stutz.dontexist.com:8080/job/BukkitSpeak/102/) and see if the error still occurs?

**Comment by rogermb** [comment] 2012-10-30 11:08
Closing this now, should be fixed actually.

**Comment by graywolf336** [comment] 2012-10-30 19:54
Will test this when you get a build going on your Jenkins just to confirm with the recent updates, main reason I didn't test it was I was testing my custom build with the Herochat added onto it

**Comment by rogermb** [comment] 2012-10-30 21:31
Ah, alright.
Well, Jenkins (usually) is up-to-date with GitHub because of the GitHub hook, so you should be able to try out a build with Herochat integration and the bug fix :D
(Well, if it doesn't fail to download the herochat dependency, that is)

**Comment by rogermb** [comment] 2012-10-31 22:13
//Sadly using Herochat doesn't provide a way to do things like if they have permission to see or if they have it muted.

Wouldn't it be possible to do: 

<pre><code> Set(Insert HTML char here)Chatter> players = Herochat.getChannelManager().getChannel(BukkitSpeak.getHerochatChannel()).getMembers();
    for (Chatter ch : players) {
        if (!isMuted(ch.getPlayer()) && checkPermissions(ch.getPlayer(), "chat")) {
            ch.getPlayer().sendMessage(replaceValues(m, true));
        }
    }
</code></pre>

**Comment by graywolf336** [comment] 2012-10-31 22:17
Because of

``` java
ch.getPlayer().sendMessage(replaceValues(m, true));
```

The message wouldn't appear to be in the channel.

**Comment by graywolf336** [comment] 2012-10-31 22:23
You could probably see what the channel.getFormat() contains and maybe do something with that, but I haven't messed with it so I'm not sure how you'd do that and what all the format contains.

**Comment by rogermb** [comment] 2012-11-01 12:14
So I should just let it be like it was?
Just because I really don't want to get messing around with formatting styles of other chat plugins and all this stuff :D

**Comment by rogermb** [comment] 2012-11-01 20:18
The newest build on Jenkins should be nearly bug-free, by the way.
If you still happen to find a bug, please tell me ^^

**Comment by graywolf336** [comment] 2012-11-01 20:29
Good to see this fix "Finally fixed this stupid double messages bug!" :)

**Comment by rogermb** [comment] 2012-11-02 10:01
Yeah, I had to add some checks, but the bug actually wasn't caused by BukkitSpeak itself, but rather by the JTS3 Server Query API. This thing just kept on sending the message with "notifycliententerview" twice :D

**Comment by graywolf336** [comment] 2012-11-02 15:33
You should include the build number in the plugin's version, that way it's easy to compare dev version of the plugin... Reason I say that is because I thought you had fixed the double message and so I updated that to the build on your Jenkins which complied from that commit but I'm still getting double messages and the version I have is just 0.61-SNAPSHOT and snapshot isn't that relevant, so I'm suggesting you do something like I do in mine: https://github.com/graywolf336/CasinoSlots/blob/master/plugin.yml#L4

**Comment by graywolf336** [comment] 2012-11-02 15:35
Also, for some reason when I join the channel specified in the config it says that I left the channel instead of joining it lol

**Comment by rogermb** [comment] 2012-11-02 22:29
Lol??
It works perfectly fine for me, but I'll test it again to ensure it works correctly.

**Comment by rogermb** [comment] 2012-11-03 15:34
So I'd be ready for the update, I even found another bug and quickly fixed it.
Other than that, I was not able to reproduce the wrong messages bug, it works perfectly fine for me.
Oh, and I also added the build number to the version text :D

**Comment by graywolf336** [comment] 2012-11-03 16:46
I must of not grabbed it like I thought I did or something...interesting lol

**Comment by graywolf336** [comment] 2012-11-04 00:48
Yeah I'm still getting double messages, BUT it may not be double messages as I never get the channel enter message...

Is it possible to get the name of the channel a player joins and leaves?

Using version 0.61-SNAPSHOT-b115

**Comment by rogermb** [comment] 2012-11-04 09:37
I actually can't reproduce this issue at all, it all works perfectly fine for me.
Can we meet on a TS / MC server so you can show me the issue?

And no, channel names are not available at the moment.
I'll have to do something like the ClientList, just for channels, to give access to that.

**Comment by graywolf336** [comment] 2012-11-04 20:21
Yeah, let me know when a good time is for you to come on and I'll show you it.

Ah okay, just would be nice for having things like "Player joined the channel blah-blah". Another thing that would be sweet would be if the messages could be combined and be something like "Player left the channel <oldChannel> and joined the channel <newChannel>."

**Comment by rogermb** [comment] 2013-01-24 20:56
Mkay, I think it's time to close the issue ^^

And it's not possible to do something like "Player left the channel x and joined the channel y" because the TS server query can only listen to one single channel, and thus I don't get any "notification" if someone joins another channel :/

**Closed as completed by rogermb** 2013-01-24 20:56 UTC
Labels: Bug
